name: C++latro CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-24.04
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build clang-format g++-14

    - name: Configure Compiler
      run: |
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 100
        g++ --version

    - name: Check Formatting
      run: |
        find . -type f \( -name "*.cc" -o -name "*.hh" \) -not -path "./vendor/*" -not -path "./build/*" | xargs clang-format --dry-run --Werror

    - name: Configure Build
      run: python3 configure.py

    - name: Build
      run: ninja